### ISSUE TITLE
[Ubuntu 14.04] /etc/php5/conf.d does not exist.

### ISSUE THREAD

**Issue by caffe** [djoos-cookbooks/newrelic#299] opened 2017-05-12 20:05 UTC
Hello,

I was using release 2.0.0 in an Ubuntu 12.04 environment. Now that Ubuntu 12.04 was deprecated I'm upgrading my server to 14.04. When running the release 2.0.0 I get the following error.

`/etc/php5/conf.d does not exist.`

I then tried to run 2.28.1 but got back the following error:

`Halite is not compatible with no_lazy_load false, please set no_lazy_load true in your Chef configuration file.`

I'm using PHP 5.4. Which release do you suggest I use?

Thanks in advance,
Walter

**Comment by caffe** [comment] 2017-05-15 21:20
Hello,

I've realized the problem is that I'm using Chef 11. If I use Chef 12 AWS Opsworks won't give me the build-in recipes to run my Stack.

So, I'm not sure now if there is a fix for that. Any ideas?

Regards,
Walter

**Comment by djoos** [comment] 2017-05-16 08:47
Hi Walter,

thanks for reaching out!

Would you mind giving 2.26.0 a go?
If that doesn't help either - could you give a more verbose error trace re: `Halite is not compatible with no_lazy_load false, please set no_lazy_load true in your Chef configuration file.`?

FYI: I'll close this issue for now, as it doesn't seem to be a repo-issue. However, please provide me feedback here, so I can hopefully get you up and running with a never version than 2.0.0!

Kind regards,
David

**Closed by djoos** 2017-05-16 08:47 UTC

**Comment by caffe** [comment] 2017-05-16 19:49
Hello David,

Thank you for your reply.

I tried 2.26.0 and 2.28.1. Please see logfiles attached.

Indeed the 2.28.1 didn't generate any error related to Chef 11. Is this version Chef 11 compatible? Perhaps it's just a matter of fixing the no_lazy_load thing.

What do you think?

Kind regards,
Walter
[NewRelic_Chef11_Release2.28.1_ErrorLog.txt](https://github.com/djoos-cookbooks/newrelic/files/1005669/NewRelic_Chef11_Release2.28.1_ErrorLog.txt)
[NewRelic_Chef11_Release2.26_ErrorLog.txt](https://github.com/djoos-cookbooks/newrelic/files/1005668/NewRelic_Chef11_Release2.26_ErrorLog.txt)

**Comment by djoos** [comment] 2017-05-17 08:59
Hi Walter,

thanks for pinging over the stacktraces...

Unfortunately the issue you are experiencing seems to be caused by the New Relic-cookbook's dependencies, not directly by the New Relic-cookbook itself... :-/

- Chef 11 + 2.26
`This resource is written with Chef 12.5 custom resources, and requires at least Chef 12.0 used with the compat_resource cookbook, it will not work with Chef 11.x clients, and those users must pin their cookbooks to older versions or upgrade.`
=> [compat_resource](https://github.com/chef-cookbooks/compat_resource) cookbook, which seems to be pulled in via apt and python > build-essential. As you only need php, perhaps it's worth tweaking the dependencies and strip the ones you don't need (ie. python) and/or have a look at pinning their versions to some older version? Not elegant at all though...

- Chef 11 + 2.28.1
`Halite is not compatible with no_lazy_load false, please set no_lazy_load true in your Chef configuration file.`
=> [poise](https://github.com/poise/poise) cookbook

FYI: the reason why I asked to give 2.26.0 a spin is because I know that when we got rid of the python cookbook dependency in favour of the [poise-python cookbook](https://github.com/poise/poise-python) dependency, Chef 12 would be required. I actually need to update that in the README.md ASAP...

Please let me know which direction you're thinking of and I'd love to hear how you get on!

Kind regards,
David
